[package]
name = "mirrorup"
version = "0.1.0"
authors = ["Bhanupong Petchlert <bpetlert@gmail.com>"]
description = "A program to retrieve the latest Pacman mirror list"
documentation = "https://github.com/bpetlert/mirrorup"
homepage = "https://github.com/bpetlert/mirrorup"
repository = "https://github.com/bpetlert/mirrorup"
readme = "README.md"
license = "MIT"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3.2", default-features = false }
log = "0.4.8"
env_logger = "0.7.0"
reqwest = "0.9.20"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.40"
rayon = "1.2.0"
csv = "1.1.1"
chrono = "0.4.9"

[dev-dependencies]
regex = "1.3.1"
