[package]
name = "pacman-mirrorup"
version = "0.6.0"

authors = ["Bhanupong Petchlert <bpetlert@gmail.com>"]

description = "A program to retrieve the best and latest Pacman mirror list based on user's geography"
documentation = "https://github.com/bpetlert/pacman-mirrorup"
homepage = "https://github.com/bpetlert/pacman-mirrorup"
license = "MIT"
readme = "README.adoc"
repository = "https://github.com/bpetlert/pacman-mirrorup"

edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
chrono = "0.4.19"
clap = { version = "3.0.5", features = ["derive"] }
clap-verbosity-flag = "0.4.0"
csv = "1.1.6"
log = "0.4.14"
pretty_env_logger = "0.4.0"
rayon = "1.5.1"
reqwest = { version = "0.11.8", features = [
  "blocking",
  "gzip",
  "json",
  "rustls-tls",
], default-features = false }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"

[dev-dependencies]
regex = "1.5.4"
