[package]
name = "pacman-mirrorup"
version = "0.8.0"

authors = ["Bhanupong Petchlert <bpetlert@gmail.com>"]

description = "A program to retrieve the best and latest Pacman mirror list based on user's geography"
documentation = "https://github.com/bpetlert/pacman-mirrorup"
homepage = "https://github.com/bpetlert/pacman-mirrorup"
license = "MIT"
readme = "README.adoc"
repository = "https://github.com/bpetlert/pacman-mirrorup"

edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
chrono = { version = "0.4.22", default-features = false, features = ["clock"] }
clap = { version = "4.0.15", features = ["derive"] }
csv = "1.1.6"
mimalloc = "0.1.30"
rayon = "1.5.3"
reqwest = { version = "0.11.12", features = [
  "blocking",
  "gzip",
  "json",
  "rustls-tls",
], default-features = false }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
tracing = { version = "0.1.37", features = [
  "max_level_debug",
  "release_max_level_debug",
] }
tracing-subscriber = { version = "0.3.16", features = [
  "env-filter",
  "fmt",
], default-features = false }

[dev-dependencies]
regex = "1.6.0"
