[package]
name = "pacman-mirrorup"
version = "0.3.1"
authors = ["Bhanupong Petchlert <bpetlert@gmail.com>"]
description = "A program to retrieve the best and latest Pacman mirror list based on user's geography"
documentation = "https://github.com/bpetlert/pacman-mirrorup"
homepage = "https://github.com/bpetlert/pacman-mirrorup"
repository = "https://github.com/bpetlert/pacman-mirrorup"
readme = "README.md"
license = "MIT"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3.21", default-features = false }
log = "0.4.11"
pretty_env_logger = "0.4.0"
anyhow = "1.0.34"
reqwest = { version = "0.10.9", features = ["blocking", "gzip", "json", "rustls-tls"], default-features = false }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
rayon = "1.5.0"
csv = "1.1.5"
chrono = "0.4.19"

[dev-dependencies]
regex = "1.4.2"
