[package]
name = "pacman-mirrorup"
version = "0.9.0"

authors = ["Bhanupong Petchlert <bpetlert@gmail.com>"]

description = "A program to retrieve the best and latest Pacman mirror list based on user's geography"
documentation = "https://github.com/bpetlert/pacman-mirrorup"
homepage = "https://github.com/bpetlert/pacman-mirrorup"
license = "GPL-3.0-or-later"
readme = "README.adoc"
repository = "https://github.com/bpetlert/pacman-mirrorup"

edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.66"
chrono = { version = "0.4.23", default-features = false, features = ["clock"] }
clap = { version = "4.0.29", features = ["derive"] }
csv = "1.1.6"
mimalloc = "0.1.32"
rayon = "1.6.1"
reqwest = { version = "0.11.13", features = [
  "blocking",
  "gzip",
  "json",
  "rustls-tls",
], default-features = false }
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
tracing = { version = "0.1.37", features = [
  "max_level_debug",
  "release_max_level_debug",
] }
tracing-subscriber = { version = "0.3.16", features = [
  "env-filter",
  "fmt",
], default-features = false }

[dev-dependencies]
regex = "1.7.0"
