[package]
name = "pacman-mirrorup"
version = "0.7.0"

authors = ["Bhanupong Petchlert <bpetlert@gmail.com>"]

description = "A program to retrieve the best and latest Pacman mirror list based on user's geography"
documentation = "https://github.com/bpetlert/pacman-mirrorup"
homepage = "https://github.com/bpetlert/pacman-mirrorup"
license = "MIT"
readme = "README.adoc"
repository = "https://github.com/bpetlert/pacman-mirrorup"

edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
csv = "1.1.6"
rayon = "1.5.3"
reqwest = { version = "0.11.11", features = [
  "blocking",
  "gzip",
  "json",
  "rustls-tls",
], default-features = false }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
time = { version = "0.3.13", features = ["local-offset", "formatting"] }
tracing = { version = "0.1.36", features = [
  "max_level_debug",
  "release_max_level_info",
] }
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }

[dev-dependencies]
regex = "1.6.0"
