[package]
name = "pacman-mirrorup"
version = "0.11.0"

authors = ["Bhanupong Petchlert <bpetlert@gmail.com>"]

description = "A program to retrieve the best and latest Pacman mirror list based on user's geography"
documentation = "https://github.com/bpetlert/pacman-mirrorup"
homepage = "https://github.com/bpetlert/pacman-mirrorup"
license = "GPL-3.0-or-later"
readme = "README.adoc"
repository = "https://github.com/bpetlert/pacman-mirrorup"

edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.70"
chrono = { version = "0.4.24", default-features = false, features = ["clock"] }
clap = { version = "4.2.2", features = ["derive"] }
csv = "1.2.1"
mimalloc = "0.1.36"
once_cell = "1.17.1"
rayon = "1.7.0"
regex = "1.7.3"
reqwest = { version = "0.11.16", features = [
  "blocking",
  "gzip",
  "json",
  "rustls-tls",
], default-features = false }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tracing = { version = "0.1.37", features = [
  "max_level_debug",
  "release_max_level_debug",
] }
tracing-subscriber = { version = "0.3.16", features = [
  "env-filter",
  "fmt",
], default-features = false }
